name: owl_live_stats
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_webview_plugin: 0.1.6
  http: 0.11.3+16
  json_annotation: ^0.2.3
  shared_preferences: ^0.4.2
  async_loader: 0.1.1
  cached_network_image: ^0.4.1
  intl: ^0.15.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.8.9
  json_serializable: 0.5.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  ## Team logos
    - images/owl-splash.png
    - images/owl-splash-small.png
    - images/owl-splash-smaller.png
    - images/team-4402-logo.png
    - images/team-4403-logo.png
    - images/team-4404-logo.png
    - images/team-4405-logo.png
    - images/team-4406-logo.png
    - images/team-4407-logo.png
    - images/team-4408-logo.png
    - images/team-4409-logo.png
    - images/team-4410-logo.png
    - images/team-4523-logo.png
    - images/team-4524-logo.png
    - images/team-4525-logo.png
  ## Small team logos
    - images/team-4402-logo-small.png
    - images/team-4403-logo-small.png
    - images/team-4404-logo-small.png
    - images/team-4405-logo-small.png
    - images/team-4406-logo-small.png
    - images/team-4407-logo-small.png
    - images/team-4408-logo-small.png
    - images/team-4409-logo-small.png
    - images/team-4410-logo-small.png
    - images/team-4523-logo-small.png
    - images/team-4524-logo-small.png
    - images/team-4525-logo-small.png
  ## Map types
    - images/map_type_assault.png
    - images/map_type_escort.png
    - images/map_type_control.png
    - images/map_type_hybrid.png
  ## Maps
    - images/maps/blizzard-world.jpg
    - images/maps/dorado.jpg
    - images/maps/eichenwalde.jpg
    - images/maps/gibraltar.jpg
    - images/maps/hanamura.jpg
    - images/maps/hollywood.jpg
    - images/maps/horizon-lunar-colony.jpg
    - images/maps/ilios.jpg
    - images/maps/junkertown.jpg
    - images/maps/kings-row.jpg
    - images/maps/lijiang.jpg
    - images/maps/nepal.jpg
    - images/maps/numbani.jpg
    - images/maps/oasis.jpg
    - images/maps/rialto.jpg
    - images/maps/route-66.jpg
    - images/maps/temple-of-anubis.jpg
    - images/maps/volskaya-industries.jpg
    - images/roles/support.png
    - images/roles/tank.png
    - images/roles/offense.png
    - images/roles/flex.png
  ## Icons
    - images/battle-icon.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Alte
      fonts:
        - asset: fonts/alte-mittel-regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
